steps:
  # Step 1: Install dependencies
  - name: "node:18"
    dir: "frontend"
    entrypoint: "npm"
    args: ["install"]

  # Step 2: Build React App (dengan chmod)
  - name: "node:18"
    dir: "frontend"
    entrypoint: "bash"
    args:
      - -c
      - |
        chmod +x ./node_modules/.bin/react-scripts && \
        npm run build

  # Step 3: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "frontend"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy ../app.yaml",
      ]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY
